<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AttributeTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('attributes')->delete();

        $now = Carbon::now();

        DB::table('attributes')->insert([
            [
                'id'                  => '1',
                'code'                => 'sku',
                'admin_name'          => 'SKU',
                'type'                => 'text',
                'validation'          => NULL,
                'position'            => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '2',
                'code'                => 'name',
                'admin_name'          => 'Name',
                'type'                => 'text',
                'validation'          => NULL,
                'position'            => '2',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '3',
                'code'                => 'url_key',
                'admin_name'          => 'URL Key',
                'type'                => 'text',
                'validation'          => NULL,
                'position'            => '3',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '4',
                'code'                => 'tax_category_id',
                'admin_name'          => 'Tax Category',
                'type'                => 'select',
                'validation'          => NULL,
                'position'            => '4',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '5',
                'code'                => 'featured',
                'admin_name'          => 'Featured',
                'type'                => 'boolean',
                'validation'          => NULL,
                'position'            => '6',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '6',
                'code'                => 'visible_individually',
                'admin_name'          => 'Visible Individually',
                'type'                => 'boolean',
                'validation'          => NULL,
                'position'            => '7',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '7',
                'code'                => 'status',
                'admin_name'          => 'Status',
                'type'                => 'boolean',
                'validation'          => NULL,
                'position'            => '8',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '8',
                'code'                => 'short_description',
                'admin_name'          => 'Short Description',
                'type'                => 'textarea',
                'validation'          => NULL,
                'position'            => '9',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '9',
                'code'                => 'description',
                'admin_name'          => 'Description',
                'type'                => 'textarea',
                'validation'          => NULL,
                'position'            => '10',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '10',
                'code'                => 'price',
                'admin_name'          => 'Price',
                'type'                => 'price',
                'validation'          => 'decimal',
                'position'            => '11',
                'is_filterable'       => '1',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '11',
                'code'                => 'special_price',
                'admin_name'          => 'Special Price',
                'type'                => 'price',
                'validation'          => 'decimal',
                'position'            => '13',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '12',
                'code'                => 'meta_title',
                'admin_name'          => 'Meta Title',
                'type'                => 'textarea',
                'validation'          => NULL,
                'position'            => '16',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '13',
                'code'                => 'meta_keywords',
                'admin_name'          => 'Meta Keywords',
                'type'                => 'textarea',
                'validation'          => NULL,
                'position'            => '17',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '14',
                'code'                => 'meta_description',
                'admin_name'          => 'Meta Description',
                'type'                => 'textarea',
                'validation'          => NULL,
                'position'            => '18',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '15',
                'code'                => 'width',
                'admin_name'          => 'Width',
                'type'                => 'text',
                'validation'          => 'decimal',
                'position'            => '19',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '16',
                'code'                => 'height',
                'admin_name'          => 'Height',
                'type'                => 'text',
                'validation'          => 'decimal',
                'position'            => '20',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '17',
                'code'                => 'depth',
                'admin_name'          => 'Depth',
                'type'                => 'text',
                'validation'          => 'decimal',
                'position'            => '21',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '18',
                'code'                => 'weight',
                'admin_name'          => 'Weight',
                'type'                => 'text',
                'validation'          => 'decimal',
                'position'            => '22',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '19',
                'code'                => 'color',
                'admin_name'          => 'Color',
                'type'                => 'select',
                'validation'          => NULL,
                'position'            => '23',
                'is_filterable'       => '1',
                'is_configurable'     => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => '20',
                'code'                => 'size',
                'admin_name'          => 'Size',
                'type'                => 'select',
                'validation'          => NULL,
                'position'            => '24',
                'is_filterable'       => '1',
                'is_configurable'     => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'id'                  => '21',
                'code'                => 'material',
                'admin_name'          => 'Material',
                'type'                => 'select',
                'validation'          => NULL,
                'position'            => '27',
                'is_filterable'       => '1',
                'is_configurable'     => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
            [
                'id'                  => '22',
                'code'                => 'medium',
                'admin_name'          => 'Medium',
                'type'                => 'select',
                'validation'          => NULL,
                'position'            => '28',
                'is_filterable'       => '1',
                'is_configurable'     => '1',
                'is_user_defined'     => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
            ]
        ]);
    }
}
